# Generated by Django 5.0.7 on 2024-09-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField(default='defautpasswordfortesting')),
                ('email', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'projects_users',
            },
        ),
    ]
